pipeline {
    agent {
        docker {
            image 'python:3.11-slim'
            args '-v /home/app:/home/app'
        }
    }

    environment {
        PYTHON_VERSION = '3.11.2'
        VENV_DIR = 'venv'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: 'refs/heads/main']], userRemoteConfigs: [[url: 'https://github.com/dawidziel/szaszki-chess.git']]])
            }
        }

        stage('Set up Python') {
            steps {
                // Install git in the container
                sh "apt-get update -y && apt-get install -y git"
                // Container already has Python so only set up virtualenv
                sh "python3 -m venv ${VENV_DIR}"
                sh ". ${VENV_DIR}/bin/activate && python -m pip install --upgrade pip"
            }
        }

        stage('Install Clickable') {
            steps {
                sh ". ${VENV_DIR}/bin/activate && pip install git+https://gitlab.com/clickable/clickable.git"
            }
        }

        stage('Build the game') {
            steps {
                sh ". ${VENV_DIR}/bin/activate && clickable build"
            }
        }

        stage('Compile for Ubuntu Touch') {
            steps {
                // Compile for Ubuntu Touch using clickable build target
                sh ". ${VENV_DIR}/bin/activate && clickable build --target ubuntu-touch"
                // Create target directory and copy compiled app
                sh "mkdir -p /home/app"
                sh "cp -r build/* /home/app/"
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: '**/build/**/*', allowEmptyArchive: true
        }
    }
}