pipeline {
    agent any

    environment {
        PYTHON_VERSION = '3.11.2'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: 'main']], userRemoteConfigs: [[url: 'https://github.com/dawidziel/szaszki-chess.git']]])
            }
        }

        stage('Set up Python') {
            steps {
                sh 'sudo apt-get update'
                sh 'sudo apt-get install -y python3 python3-pip'
                sh 'python3 -m pip install --upgrade pip'
            }
        }

        stage('Install Clickable') {
            steps {
                sh 'pip install git+https://gitlab.com/clickable/clickable.git'
            }
        }

        stage('Build the game') {
            steps {
                sh 'clickable build'
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: '**/build/**/*', allowEmptyArchive: true
        }
    }
}